piVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: frontend
        image: gladysgodwin/project-frontend:2024
        ports:
        - containerPort: 80
      - name: backend
        image: gladysgodwin/project-backend:2024
        ports:
        - containerPort: 3000
      - name: database
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: postgres-url
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}