apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: app
spec:
  selector:
    app: website
  ports:
    - name: frontend
      port: 80
      protocol: TCP
      targetPort: 80
    - name: frontend-https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: backend
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer